### ISSUE TITLE
problem with textDelimiter when converting to CSV

### ISSUE THREAD

**Issue by zidenis** [close2/csv#5] opened 2016-02-28 21:38 UTC
I'm trying to use csv-3.0.1 to parse some csv files. The conversion from CSV to List is ok, but I'm experiencing a strange behavior when converting a list to CSV. The problem is that the converter does not produce the text Delimiter, even though I try to force it. Here is one example:

# Source
$ cat test.dart
```dart
import 'package:csv/csv.dart';

var csvStr = '''
"Alice","Austria",1
"Bob",",Brazil",2
''';

main() {
  var rowsAsLists = const CsvToListConverter(eol: '\n').convert(csvStr);
  print(rowsAsLists);
  var listsAsRows = const ListToCsvConverter().convert(rowsAsLists);
  print(listsAsRows);
  listsAsRows = const ListToCsvConverter().convert(rowsAsLists, textDelimiter: '#');
  print(listsAsRows);
}
```

# Result

$ dart test.dart
```dart
[[Alice, Austria, 1], [Bob, ,Brazil, 2]]
Alice,Austria,1
Bob,",Brazil",2
Alice,Austria,1
Bob,#,Brazil",2
```

Look that the delimiter was shown when the string begins with the field separator.
I'm using... 
Dart VM version: 1.14.0 (Thu Jan 28 09:20:03 2016) on "macos_x64"

**Comment by close2** [comment] 2016-03-18 09:36
sorry for the delay.  My notification settings were incorrect.  Will be fixed soon.

**Comment by close2** [comment] 2016-03-18 09:53
Just to clarify.
Not displaying delimiters is not a bug.  Using " as the endDelimiter in the example is.
The last line should read: «Bob,#,Brazil#,2»

Another part of this bug is, that numbers should always be delimited if they are strings.
(If for instance shouldParseNumbers: false is set)

However I will add an option to force delimiters for all fields.

**Closed** 2016-03-26 18:19 UTC
Labels: bug, enhancement
